[platformio]
src_dir = source

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

build_flags = 
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=3
    ; Cấu hình cho LVGL v8
    -DLV_CONF_SKIP
    -DLV_COLOR_DEPTH=16
    ; Cấu hình cho TFT_eSPI (Màn hình 2.8 inch)
    -DUSER_SETUP_LOADED=1
    -DST7789_DRIVER=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=320
    -DTFT_RGB_ORDER=TFT_BGR
    -DTFT_INVERSION_ON

lib_deps = 
    bodmer/TFT_eSPI@^2.5.43
    lvgl/lvgl@^8.3.11
    bblanchon/ArduinoJson@^7.0.4