[env:esp32s3-2.8inch]
platform = espressif32
board = esp32s3
framework = arduino

; Tốc độ truyền Serial Monitor để xem log
monitor_speed = 115200

; Tự động mở Serial Monitor ngay sau khi nạp code thành công
monitor_filters = esp32_exception_decoder, time

; Cấu hình bộ nhớ PSRAM cho ESP32-S3 (Rất quan trọng cho màn hình & AI Audio)
board_build.arduino.memory_type = qio_opi
build_flags = 
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=3

; Quản lý thư viện tự động (PlatformIO tự tải trên Internet về)
lib_deps = 
    bodmer/TFT_eSPI @ ^2.5.43          ; Thư viện lái màn hình 2.8 inch
    lvgl/lvgl @ ^8.3.11                ; Thư viện vẽ giao diện/biểu cảm Robot
    schreibfaul1/ESP32-AudioI2S @ ^3.0.6 ; Thư viện phát âm thanh qua I2S
    bblanchon/ArduinoJson @ ^7.0.4     ; Thư viện xử lý dữ liệu JSON từ AI